// HTS-KGA API sözleşmesi (T-E06-01, ADR-12, ADR-33).
//
// # Geometri alanları neden `string`
//
// ADR-12/2: GeoJSON **veritabanında** üretilir (`ST_AsGeoJSON`). Proto tarafında
// alan tipi GeoJSON metnidir; uygulama katmanında geometri dönüşüm kodu
// yazılmaz. Bir `Polygon` mesajı tanımlamak, PostGIS'in zaten ürettiği
// çıktıyı çözüp yeniden kurmak olurdu.
//
// # grpc-gateway kullanılmaz
//
// ADR-12/1: REST handler'ları **elle** yazılır ve gRPC ile aynı servis
// katmanını çağırır. Bu dosya iki tarafın da ortak sözleşmesidir; aralarında
// kod üretimi yoktur.
//
// # ground_truth burada yok ve olmayacak
//
// ADR-33/2: gateway gerçek konumu göremez (`svc_gateway` rolünün yetkisi yok).
// Bu sözleşmede gerçek konum taşıyan bir alan tanımlanmaz — kör test (K6)
// API katmanına kadar uzar.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/hts/v1/hts.proto

package htsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BoundingBox, viewport süzgecidir (ADR-13: harita hareketinde ST_Intersects).
type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinLon        float64                `protobuf:"fixed64,1,opt,name=min_lon,json=minLon,proto3" json:"min_lon,omitempty"`
	MinLat        float64                `protobuf:"fixed64,2,opt,name=min_lat,json=minLat,proto3" json:"min_lat,omitempty"`
	MaxLon        float64                `protobuf:"fixed64,3,opt,name=max_lon,json=maxLon,proto3" json:"max_lon,omitempty"`
	MaxLat        float64                `protobuf:"fixed64,4,opt,name=max_lat,json=maxLat,proto3" json:"max_lat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{0}
}

func (x *BoundingBox) GetMinLon() float64 {
	if x != nil {
		return x.MinLon
	}
	return 0
}

func (x *BoundingBox) GetMinLat() float64 {
	if x != nil {
		return x.MinLat
	}
	return 0
}

func (x *BoundingBox) GetMaxLon() float64 {
	if x != nil {
		return x.MaxLon
	}
	return 0
}

func (x *BoundingBox) GetMaxLat() float64 {
	if x != nil {
		return x.MaxLat
	}
	return 0
}

// TimeRange, zaman aralığı süzgecidir (ADR-13: varsayılan 1 gün).
type TimeRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFC3339. Boşsa sunucu varsayılanı uygular.
	From          string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{1}
}

func (x *TimeRange) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *TimeRange) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{2}
}

func (x *ListRunsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Run struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RunId            string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Scenario         string                 `protobuf:"bytes,2,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Morphology       string                 `protobuf:"bytes,3,opt,name=morphology,proto3" json:"morphology,omitempty"`
	Seed             int64                  `protobuf:"varint,4,opt,name=seed,proto3" json:"seed,omitempty"`
	StartedAt        string                 `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt       string                 `protobuf:"bytes,6,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	PublishedEvents  int64                  `protobuf:"varint,7,opt,name=published_events,json=publishedEvents,proto3" json:"published_events,omitempty"`
	AnalyzedEvents   int64                  `protobuf:"varint,8,opt,name=analyzed_events,json=analyzedEvents,proto3" json:"analyzed_events,omitempty"`
	InspectedRecords int64                  `protobuf:"varint,9,opt,name=inspected_records,json=inspectedRecords,proto3" json:"inspected_records,omitempty"`
	// Lambda, kalibre edilmiş belirsizlik ölçeğidir (ADR-02). Boşsa kalibre
	// edilmemiş.
	Lambda        float64 `protobuf:"fixed64,10,opt,name=lambda,proto3" json:"lambda,omitempty"`
	HasLambda     bool    `protobuf:"varint,11,opt,name=has_lambda,json=hasLambda,proto3" json:"has_lambda,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{3}
}

func (x *Run) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Run) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *Run) GetMorphology() string {
	if x != nil {
		return x.Morphology
	}
	return ""
}

func (x *Run) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *Run) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *Run) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *Run) GetPublishedEvents() int64 {
	if x != nil {
		return x.PublishedEvents
	}
	return 0
}

func (x *Run) GetAnalyzedEvents() int64 {
	if x != nil {
		return x.AnalyzedEvents
	}
	return 0
}

func (x *Run) GetInspectedRecords() int64 {
	if x != nil {
		return x.InspectedRecords
	}
	return 0
}

func (x *Run) GetLambda() float64 {
	if x != nil {
		return x.Lambda
	}
	return 0
}

func (x *Run) GetHasLambda() bool {
	if x != nil {
		return x.HasLambda
	}
	return false
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*Run                 `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{4}
}

func (x *ListRunsResponse) GetRuns() []*Run {
	if x != nil {
		return x.Runs
	}
	return nil
}

// GeoJsonResponse, tüm harita uçlarının ortak yanıtıdır.
//
// `feature_collection` doğrudan PostGIS'ten gelen GeoJSON metnidir (ADR-12/2).
type GeoJsonResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FeatureCollection string                 `protobuf:"bytes,1,opt,name=feature_collection,json=featureCollection,proto3" json:"feature_collection,omitempty"`
	// Count, koleksiyondaki geometri sayısıdır (ADR-13 sınır denetimi için).
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// Truncated her zaman false'tur: sınır aşılırsa istek REDDEDİLİR (400),
	// sessizce kırpılmaz. Alan, sözleşmenin bu davranışı açıkça beyan etmesi
	// için vardır.
	Truncated     bool `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoJsonResponse) Reset() {
	*x = GeoJsonResponse{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoJsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoJsonResponse) ProtoMessage() {}

func (x *GeoJsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoJsonResponse.ProtoReflect.Descriptor instead.
func (*GeoJsonResponse) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{5}
}

func (x *GeoJsonResponse) GetFeatureCollection() string {
	if x != nil {
		return x.FeatureCollection
	}
	return ""
}

func (x *GeoJsonResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GeoJsonResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type GetCellsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Bbox          *BoundingBox           `protobuf:"bytes,2,opt,name=bbox,proto3" json:"bbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellsRequest) Reset() {
	*x = GetCellsRequest{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellsRequest) ProtoMessage() {}

func (x *GetCellsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellsRequest.ProtoReflect.Descriptor instead.
func (*GetCellsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{6}
}

func (x *GetCellsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetCellsRequest) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

type GetEstimatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// Subscriber, `pseudo_msisdn`'dir (ADR-33/3). ADR-13 zorunlu kılar.
	Subscriber string     `protobuf:"bytes,2,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	TimeRange  *TimeRange `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	// Method: "B0" | "B1" | "M". Boşsa hepsi.
	Method string `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	// Confidence: 0.50 | 0.90 | 0.95. 0 ise hepsi.
	Confidence    float64      `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Bbox          *BoundingBox `protobuf:"bytes,6,opt,name=bbox,proto3" json:"bbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEstimatesRequest) Reset() {
	*x = GetEstimatesRequest{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEstimatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEstimatesRequest) ProtoMessage() {}

func (x *GetEstimatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEstimatesRequest.ProtoReflect.Descriptor instead.
func (*GetEstimatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{7}
}

func (x *GetEstimatesRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetEstimatesRequest) GetSubscriber() string {
	if x != nil {
		return x.Subscriber
	}
	return ""
}

func (x *GetEstimatesRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *GetEstimatesRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *GetEstimatesRequest) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *GetEstimatesRequest) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

type GetFindingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RunId string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// RuleId: 1..5. 0 ise hepsi.
	RuleId    int32        `protobuf:"varint,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	TimeRange *TimeRange   `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Bbox      *BoundingBox `protobuf:"bytes,4,opt,name=bbox,proto3" json:"bbox,omitempty"`
	// CanonicalOnly true ise yalnızca kanonik bulgular (ADR-28/4).
	CanonicalOnly bool `protobuf:"varint,5,opt,name=canonical_only,json=canonicalOnly,proto3" json:"canonical_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFindingsRequest) Reset() {
	*x = GetFindingsRequest{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFindingsRequest) ProtoMessage() {}

func (x *GetFindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFindingsRequest.ProtoReflect.Descriptor instead.
func (*GetFindingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{8}
}

func (x *GetFindingsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetFindingsRequest) GetRuleId() int32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *GetFindingsRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *GetFindingsRequest) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *GetFindingsRequest) GetCanonicalOnly() bool {
	if x != nil {
		return x.CanonicalOnly
	}
	return false
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{9}
}

func (x *GetMetricsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type MetricRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenario      string                 `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	PartitionKey  string                 `protobuf:"bytes,4,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	NEvents       int64                  `protobuf:"varint,5,opt,name=n_events,json=nEvents,proto3" json:"n_events,omitempty"`
	CoverageRate  float64                `protobuf:"fixed64,6,opt,name=coverage_rate,json=coverageRate,proto3" json:"coverage_rate,omitempty"`
	MedianAreaKm2 float64                `protobuf:"fixed64,7,opt,name=median_area_km2,json=medianAreaKm2,proto3" json:"median_area_km2,omitempty"`
	P90AreaKm2    float64                `protobuf:"fixed64,8,opt,name=p90_area_km2,json=p90AreaKm2,proto3" json:"p90_area_km2,omitempty"`
	R50M          float64                `protobuf:"fixed64,9,opt,name=r50_m,json=r50M,proto3" json:"r50_m,omitempty"`
	R95M          float64                `protobuf:"fixed64,10,opt,name=r95_m,json=r95M,proto3" json:"r95_m,omitempty"`
	P95PartCount  int32                  `protobuf:"varint,11,opt,name=p95_part_count,json=p95PartCount,proto3" json:"p95_part_count,omitempty"`
	RepairedRatio float64                `protobuf:"fixed64,12,opt,name=repaired_ratio,json=repairedRatio,proto3" json:"repaired_ratio,omitempty"`
	ReductionVsB0 float64                `protobuf:"fixed64,13,opt,name=reduction_vs_b0,json=reductionVsB0,proto3" json:"reduction_vs_b0,omitempty"`
	ReductionVsB1 float64                `protobuf:"fixed64,14,opt,name=reduction_vs_b1,json=reductionVsB1,proto3" json:"reduction_vs_b1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricRow) Reset() {
	*x = MetricRow{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricRow) ProtoMessage() {}

func (x *MetricRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricRow.ProtoReflect.Descriptor instead.
func (*MetricRow) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{10}
}

func (x *MetricRow) GetScenario() string {
	if x != nil {
		return x.Scenario
	}
	return ""
}

func (x *MetricRow) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MetricRow) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *MetricRow) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *MetricRow) GetNEvents() int64 {
	if x != nil {
		return x.NEvents
	}
	return 0
}

func (x *MetricRow) GetCoverageRate() float64 {
	if x != nil {
		return x.CoverageRate
	}
	return 0
}

func (x *MetricRow) GetMedianAreaKm2() float64 {
	if x != nil {
		return x.MedianAreaKm2
	}
	return 0
}

func (x *MetricRow) GetP90AreaKm2() float64 {
	if x != nil {
		return x.P90AreaKm2
	}
	return 0
}

func (x *MetricRow) GetR50M() float64 {
	if x != nil {
		return x.R50M
	}
	return 0
}

func (x *MetricRow) GetR95M() float64 {
	if x != nil {
		return x.R95M
	}
	return 0
}

func (x *MetricRow) GetP95PartCount() int32 {
	if x != nil {
		return x.P95PartCount
	}
	return 0
}

func (x *MetricRow) GetRepairedRatio() float64 {
	if x != nil {
		return x.RepairedRatio
	}
	return 0
}

func (x *MetricRow) GetReductionVsB0() float64 {
	if x != nil {
		return x.ReductionVsB0
	}
	return 0
}

func (x *MetricRow) GetReductionVsB1() float64 {
	if x != nil {
		return x.ReductionVsB1
	}
	return 0
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*MetricRow           `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{11}
}

func (x *GetMetricsResponse) GetRows() []*MetricRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type GetIntegrityMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntegrityMetricsRequest) Reset() {
	*x = GetIntegrityMetricsRequest{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntegrityMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrityMetricsRequest) ProtoMessage() {}

func (x *GetIntegrityMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrityMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetIntegrityMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{12}
}

func (x *GetIntegrityMetricsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type IntegrityMetricRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        int32                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleName      string                 `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Findings      int64                  `protobuf:"varint,3,opt,name=findings,proto3" json:"findings,omitempty"`
	TruePositives int64                  `protobuf:"varint,4,opt,name=true_positives,json=truePositives,proto3" json:"true_positives,omitempty"`
	Injected      int64                  `protobuf:"varint,5,opt,name=injected,proto3" json:"injected,omitempty"`
	Precision     float64                `protobuf:"fixed64,6,opt,name=precision,proto3" json:"precision,omitempty"`
	HasPrecision  bool                   `protobuf:"varint,7,opt,name=has_precision,json=hasPrecision,proto3" json:"has_precision,omitempty"`
	Recall        float64                `protobuf:"fixed64,8,opt,name=recall,proto3" json:"recall,omitempty"`
	PrecisionLo   float64                `protobuf:"fixed64,9,opt,name=precision_lo,json=precisionLo,proto3" json:"precision_lo,omitempty"`
	PrecisionHi   float64                `protobuf:"fixed64,10,opt,name=precision_hi,json=precisionHi,proto3" json:"precision_hi,omitempty"`
	Sufficient    bool                   `protobuf:"varint,11,opt,name=sufficient,proto3" json:"sufficient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrityMetricRow) Reset() {
	*x = IntegrityMetricRow{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrityMetricRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrityMetricRow) ProtoMessage() {}

func (x *IntegrityMetricRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrityMetricRow.ProtoReflect.Descriptor instead.
func (*IntegrityMetricRow) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{13}
}

func (x *IntegrityMetricRow) GetRuleId() int32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *IntegrityMetricRow) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *IntegrityMetricRow) GetFindings() int64 {
	if x != nil {
		return x.Findings
	}
	return 0
}

func (x *IntegrityMetricRow) GetTruePositives() int64 {
	if x != nil {
		return x.TruePositives
	}
	return 0
}

func (x *IntegrityMetricRow) GetInjected() int64 {
	if x != nil {
		return x.Injected
	}
	return 0
}

func (x *IntegrityMetricRow) GetPrecision() float64 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *IntegrityMetricRow) GetHasPrecision() bool {
	if x != nil {
		return x.HasPrecision
	}
	return false
}

func (x *IntegrityMetricRow) GetRecall() float64 {
	if x != nil {
		return x.Recall
	}
	return 0
}

func (x *IntegrityMetricRow) GetPrecisionLo() float64 {
	if x != nil {
		return x.PrecisionLo
	}
	return 0
}

func (x *IntegrityMetricRow) GetPrecisionHi() float64 {
	if x != nil {
		return x.PrecisionHi
	}
	return 0
}

func (x *IntegrityMetricRow) GetSufficient() bool {
	if x != nil {
		return x.Sufficient
	}
	return false
}

type GetIntegrityMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*IntegrityMetricRow  `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntegrityMetricsResponse) Reset() {
	*x = GetIntegrityMetricsResponse{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntegrityMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrityMetricsResponse) ProtoMessage() {}

func (x *GetIntegrityMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrityMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetIntegrityMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{14}
}

func (x *GetIntegrityMetricsResponse) GetRows() []*IntegrityMetricRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

// CellActivityRequest, k-anonim hücre yoğunluğu ucudur (ADR-33/5).
type GetCellActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Bbox          *BoundingBox           `protobuf:"bytes,2,opt,name=bbox,proto3" json:"bbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCellActivityRequest) Reset() {
	*x = GetCellActivityRequest{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellActivityRequest) ProtoMessage() {}

func (x *GetCellActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellActivityRequest.ProtoReflect.Descriptor instead.
func (*GetCellActivityRequest) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{15}
}

func (x *GetCellActivityRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetCellActivityRequest) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

// CellActivityResponse, k=5 eşiğini geçen hücreleri döndürür.
//
// `suppressed_cells`, k eşiği nedeniyle **gizlenen** hücre sayısıdır. Gizleme
// sessiz olmaz: kaç grubun bastırıldığı raporlanır.
type GetCellActivityResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FeatureCollection string                 `protobuf:"bytes,1,opt,name=feature_collection,json=featureCollection,proto3" json:"feature_collection,omitempty"`
	Count             int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	SuppressedCells   int32                  `protobuf:"varint,3,opt,name=suppressed_cells,json=suppressedCells,proto3" json:"suppressed_cells,omitempty"`
	K                 int32                  `protobuf:"varint,4,opt,name=k,proto3" json:"k,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetCellActivityResponse) Reset() {
	*x = GetCellActivityResponse{}
	mi := &file_proto_hts_v1_hts_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCellActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCellActivityResponse) ProtoMessage() {}

func (x *GetCellActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hts_v1_hts_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCellActivityResponse.ProtoReflect.Descriptor instead.
func (*GetCellActivityResponse) Descriptor() ([]byte, []int) {
	return file_proto_hts_v1_hts_proto_rawDescGZIP(), []int{16}
}

func (x *GetCellActivityResponse) GetFeatureCollection() string {
	if x != nil {
		return x.FeatureCollection
	}
	return ""
}

func (x *GetCellActivityResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetCellActivityResponse) GetSuppressedCells() int32 {
	if x != nil {
		return x.SuppressedCells
	}
	return 0
}

func (x *GetCellActivityResponse) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

var File_proto_hts_v1_hts_proto protoreflect.FileDescriptor

const file_proto_hts_v1_hts_proto_rawDesc = "" +
	"\n" +
	"\x16proto/hts/v1/hts.proto\x12\x06hts.v1\"q\n" +
	"\vBoundingBox\x12\x17\n" +
	"\amin_lon\x18\x01 \x01(\x01R\x06minLon\x12\x17\n" +
	"\amin_lat\x18\x02 \x01(\x01R\x06minLat\x12\x17\n" +
	"\amax_lon\x18\x03 \x01(\x01R\x06maxLon\x12\x17\n" +
	"\amax_lat\x18\x04 \x01(\x01R\x06maxLat\"/\n" +
	"\tTimeRange\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"'\n" +
	"\x0fListRunsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\xe4\x02\n" +
	"\x03Run\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1a\n" +
	"\bscenario\x18\x02 \x01(\tR\bscenario\x12\x1e\n" +
	"\n" +
	"morphology\x18\x03 \x01(\tR\n" +
	"morphology\x12\x12\n" +
	"\x04seed\x18\x04 \x01(\x03R\x04seed\x12\x1d\n" +
	"\n" +
	"started_at\x18\x05 \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\x06 \x01(\tR\n" +
	"finishedAt\x12)\n" +
	"\x10published_events\x18\a \x01(\x03R\x0fpublishedEvents\x12'\n" +
	"\x0fanalyzed_events\x18\b \x01(\x03R\x0eanalyzedEvents\x12+\n" +
	"\x11inspected_records\x18\t \x01(\x03R\x10inspectedRecords\x12\x16\n" +
	"\x06lambda\x18\n" +
	" \x01(\x01R\x06lambda\x12\x1d\n" +
	"\n" +
	"has_lambda\x18\v \x01(\bR\thasLambda\"3\n" +
	"\x10ListRunsResponse\x12\x1f\n" +
	"\x04runs\x18\x01 \x03(\v2\v.hts.v1.RunR\x04runs\"t\n" +
	"\x0fGeoJsonResponse\x12-\n" +
	"\x12feature_collection\x18\x01 \x01(\tR\x11featureCollection\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\"Q\n" +
	"\x0fGetCellsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12'\n" +
	"\x04bbox\x18\x02 \x01(\v2\x13.hts.v1.BoundingBoxR\x04bbox\"\xdf\x01\n" +
	"\x13GetEstimatesRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1e\n" +
	"\n" +
	"subscriber\x18\x02 \x01(\tR\n" +
	"subscriber\x120\n" +
	"\n" +
	"time_range\x18\x03 \x01(\v2\x11.hts.v1.TimeRangeR\ttimeRange\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12'\n" +
	"\x04bbox\x18\x06 \x01(\v2\x13.hts.v1.BoundingBoxR\x04bbox\"\xc6\x01\n" +
	"\x12GetFindingsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\x05R\x06ruleId\x120\n" +
	"\n" +
	"time_range\x18\x03 \x01(\v2\x11.hts.v1.TimeRangeR\ttimeRange\x12'\n" +
	"\x04bbox\x18\x04 \x01(\v2\x13.hts.v1.BoundingBoxR\x04bbox\x12%\n" +
	"\x0ecanonical_only\x18\x05 \x01(\bR\rcanonicalOnly\"*\n" +
	"\x11GetMetricsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xd5\x03\n" +
	"\tMetricRow\x12\x1a\n" +
	"\bscenario\x18\x01 \x01(\tR\bscenario\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12#\n" +
	"\rpartition_key\x18\x04 \x01(\tR\fpartitionKey\x12\x19\n" +
	"\bn_events\x18\x05 \x01(\x03R\anEvents\x12#\n" +
	"\rcoverage_rate\x18\x06 \x01(\x01R\fcoverageRate\x12&\n" +
	"\x0fmedian_area_km2\x18\a \x01(\x01R\rmedianAreaKm2\x12 \n" +
	"\fp90_area_km2\x18\b \x01(\x01R\n" +
	"p90AreaKm2\x12\x13\n" +
	"\x05r50_m\x18\t \x01(\x01R\x04r50M\x12\x13\n" +
	"\x05r95_m\x18\n" +
	" \x01(\x01R\x04r95M\x12$\n" +
	"\x0ep95_part_count\x18\v \x01(\x05R\fp95PartCount\x12%\n" +
	"\x0erepaired_ratio\x18\f \x01(\x01R\rrepairedRatio\x12&\n" +
	"\x0freduction_vs_b0\x18\r \x01(\x01R\rreductionVsB0\x12&\n" +
	"\x0freduction_vs_b1\x18\x0e \x01(\x01R\rreductionVsB1\";\n" +
	"\x12GetMetricsResponse\x12%\n" +
	"\x04rows\x18\x01 \x03(\v2\x11.hts.v1.MetricRowR\x04rows\"3\n" +
	"\x1aGetIntegrityMetricsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xea\x02\n" +
	"\x12IntegrityMetricRow\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x05R\x06ruleId\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x12\x1a\n" +
	"\bfindings\x18\x03 \x01(\x03R\bfindings\x12%\n" +
	"\x0etrue_positives\x18\x04 \x01(\x03R\rtruePositives\x12\x1a\n" +
	"\binjected\x18\x05 \x01(\x03R\binjected\x12\x1c\n" +
	"\tprecision\x18\x06 \x01(\x01R\tprecision\x12#\n" +
	"\rhas_precision\x18\a \x01(\bR\fhasPrecision\x12\x16\n" +
	"\x06recall\x18\b \x01(\x01R\x06recall\x12!\n" +
	"\fprecision_lo\x18\t \x01(\x01R\vprecisionLo\x12!\n" +
	"\fprecision_hi\x18\n" +
	" \x01(\x01R\vprecisionHi\x12\x1e\n" +
	"\n" +
	"sufficient\x18\v \x01(\bR\n" +
	"sufficient\"M\n" +
	"\x1bGetIntegrityMetricsResponse\x12.\n" +
	"\x04rows\x18\x01 \x03(\v2\x1a.hts.v1.IntegrityMetricRowR\x04rows\"X\n" +
	"\x16GetCellActivityRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12'\n" +
	"\x04bbox\x18\x02 \x01(\v2\x13.hts.v1.BoundingBoxR\x04bbox\"\x97\x01\n" +
	"\x17GetCellActivityResponse\x12-\n" +
	"\x12feature_collection\x18\x01 \x01(\tR\x11featureCollection\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12)\n" +
	"\x10suppressed_cells\x18\x03 \x01(\x05R\x0fsuppressedCells\x12\f\n" +
	"\x01k\x18\x04 \x01(\x05R\x01k2\x8c\x04\n" +
	"\n" +
	"HtsService\x12=\n" +
	"\bListRuns\x12\x17.hts.v1.ListRunsRequest\x1a\x18.hts.v1.ListRunsResponse\x12<\n" +
	"\bGetCells\x12\x17.hts.v1.GetCellsRequest\x1a\x17.hts.v1.GeoJsonResponse\x12D\n" +
	"\fGetEstimates\x12\x1b.hts.v1.GetEstimatesRequest\x1a\x17.hts.v1.GeoJsonResponse\x12B\n" +
	"\vGetFindings\x12\x1a.hts.v1.GetFindingsRequest\x1a\x17.hts.v1.GeoJsonResponse\x12C\n" +
	"\n" +
	"GetMetrics\x12\x19.hts.v1.GetMetricsRequest\x1a\x1a.hts.v1.GetMetricsResponse\x12^\n" +
	"\x13GetIntegrityMetrics\x12\".hts.v1.GetIntegrityMetricsRequest\x1a#.hts.v1.GetIntegrityMetricsResponse\x12R\n" +
	"\x0fGetCellActivity\x12\x1e.hts.v1.GetCellActivityRequest\x1a\x1f.hts.v1.GetCellActivityResponseB4Z2github.com/NUMAN-GURBUZ/hts-kga/proto/hts/v1;htsv1b\x06proto3"

var (
	file_proto_hts_v1_hts_proto_rawDescOnce sync.Once
	file_proto_hts_v1_hts_proto_rawDescData []byte
)

func file_proto_hts_v1_hts_proto_rawDescGZIP() []byte {
	file_proto_hts_v1_hts_proto_rawDescOnce.Do(func() {
		file_proto_hts_v1_hts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hts_v1_hts_proto_rawDesc), len(file_proto_hts_v1_hts_proto_rawDesc)))
	})
	return file_proto_hts_v1_hts_proto_rawDescData
}

var file_proto_hts_v1_hts_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_hts_v1_hts_proto_goTypes = []any{
	(*BoundingBox)(nil),                 // 0: hts.v1.BoundingBox
	(*TimeRange)(nil),                   // 1: hts.v1.TimeRange
	(*ListRunsRequest)(nil),             // 2: hts.v1.ListRunsRequest
	(*Run)(nil),                         // 3: hts.v1.Run
	(*ListRunsResponse)(nil),            // 4: hts.v1.ListRunsResponse
	(*GeoJsonResponse)(nil),             // 5: hts.v1.GeoJsonResponse
	(*GetCellsRequest)(nil),             // 6: hts.v1.GetCellsRequest
	(*GetEstimatesRequest)(nil),         // 7: hts.v1.GetEstimatesRequest
	(*GetFindingsRequest)(nil),          // 8: hts.v1.GetFindingsRequest
	(*GetMetricsRequest)(nil),           // 9: hts.v1.GetMetricsRequest
	(*MetricRow)(nil),                   // 10: hts.v1.MetricRow
	(*GetMetricsResponse)(nil),          // 11: hts.v1.GetMetricsResponse
	(*GetIntegrityMetricsRequest)(nil),  // 12: hts.v1.GetIntegrityMetricsRequest
	(*IntegrityMetricRow)(nil),          // 13: hts.v1.IntegrityMetricRow
	(*GetIntegrityMetricsResponse)(nil), // 14: hts.v1.GetIntegrityMetricsResponse
	(*GetCellActivityRequest)(nil),      // 15: hts.v1.GetCellActivityRequest
	(*GetCellActivityResponse)(nil),     // 16: hts.v1.GetCellActivityResponse
}
var file_proto_hts_v1_hts_proto_depIdxs = []int32{
	3,  // 0: hts.v1.ListRunsResponse.runs:type_name -> hts.v1.Run
	0,  // 1: hts.v1.GetCellsRequest.bbox:type_name -> hts.v1.BoundingBox
	1,  // 2: hts.v1.GetEstimatesRequest.time_range:type_name -> hts.v1.TimeRange
	0,  // 3: hts.v1.GetEstimatesRequest.bbox:type_name -> hts.v1.BoundingBox
	1,  // 4: hts.v1.GetFindingsRequest.time_range:type_name -> hts.v1.TimeRange
	0,  // 5: hts.v1.GetFindingsRequest.bbox:type_name -> hts.v1.BoundingBox
	10, // 6: hts.v1.GetMetricsResponse.rows:type_name -> hts.v1.MetricRow
	13, // 7: hts.v1.GetIntegrityMetricsResponse.rows:type_name -> hts.v1.IntegrityMetricRow
	0,  // 8: hts.v1.GetCellActivityRequest.bbox:type_name -> hts.v1.BoundingBox
	2,  // 9: hts.v1.HtsService.ListRuns:input_type -> hts.v1.ListRunsRequest
	6,  // 10: hts.v1.HtsService.GetCells:input_type -> hts.v1.GetCellsRequest
	7,  // 11: hts.v1.HtsService.GetEstimates:input_type -> hts.v1.GetEstimatesRequest
	8,  // 12: hts.v1.HtsService.GetFindings:input_type -> hts.v1.GetFindingsRequest
	9,  // 13: hts.v1.HtsService.GetMetrics:input_type -> hts.v1.GetMetricsRequest
	12, // 14: hts.v1.HtsService.GetIntegrityMetrics:input_type -> hts.v1.GetIntegrityMetricsRequest
	15, // 15: hts.v1.HtsService.GetCellActivity:input_type -> hts.v1.GetCellActivityRequest
	4,  // 16: hts.v1.HtsService.ListRuns:output_type -> hts.v1.ListRunsResponse
	5,  // 17: hts.v1.HtsService.GetCells:output_type -> hts.v1.GeoJsonResponse
	5,  // 18: hts.v1.HtsService.GetEstimates:output_type -> hts.v1.GeoJsonResponse
	5,  // 19: hts.v1.HtsService.GetFindings:output_type -> hts.v1.GeoJsonResponse
	11, // 20: hts.v1.HtsService.GetMetrics:output_type -> hts.v1.GetMetricsResponse
	14, // 21: hts.v1.HtsService.GetIntegrityMetrics:output_type -> hts.v1.GetIntegrityMetricsResponse
	16, // 22: hts.v1.HtsService.GetCellActivity:output_type -> hts.v1.GetCellActivityResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_hts_v1_hts_proto_init() }
func file_proto_hts_v1_hts_proto_init() {
	if File_proto_hts_v1_hts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hts_v1_hts_proto_rawDesc), len(file_proto_hts_v1_hts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hts_v1_hts_proto_goTypes,
		DependencyIndexes: file_proto_hts_v1_hts_proto_depIdxs,
		MessageInfos:      file_proto_hts_v1_hts_proto_msgTypes,
	}.Build()
	File_proto_hts_v1_hts_proto = out.File
	file_proto_hts_v1_hts_proto_goTypes = nil
	file_proto_hts_v1_hts_proto_depIdxs = nil
}
