// HTS-KGA API sözleşmesi (T-E06-01, ADR-12, ADR-33).
//
// # Geometri alanları neden `string`
//
// ADR-12/2: GeoJSON **veritabanında** üretilir (`ST_AsGeoJSON`). Proto tarafında
// alan tipi GeoJSON metnidir; uygulama katmanında geometri dönüşüm kodu
// yazılmaz. Bir `Polygon` mesajı tanımlamak, PostGIS'in zaten ürettiği
// çıktıyı çözüp yeniden kurmak olurdu.
//
// # grpc-gateway kullanılmaz
//
// ADR-12/1: REST handler'ları **elle** yazılır ve gRPC ile aynı servis
// katmanını çağırır. Bu dosya iki tarafın da ortak sözleşmesidir; aralarında
// kod üretimi yoktur.
//
// # ground_truth burada yok ve olmayacak
//
// ADR-33/2: gateway gerçek konumu göremez (`svc_gateway` rolünün yetkisi yok).
// Bu sözleşmede gerçek konum taşıyan bir alan tanımlanmaz — kör test (K6)
// API katmanına kadar uzar.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: proto/hts/v1/hts.proto

package htsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HtsService_ListRuns_FullMethodName            = "/hts.v1.HtsService/ListRuns"
	HtsService_GetCells_FullMethodName            = "/hts.v1.HtsService/GetCells"
	HtsService_GetEstimates_FullMethodName        = "/hts.v1.HtsService/GetEstimates"
	HtsService_GetFindings_FullMethodName         = "/hts.v1.HtsService/GetFindings"
	HtsService_GetMetrics_FullMethodName          = "/hts.v1.HtsService/GetMetrics"
	HtsService_GetIntegrityMetrics_FullMethodName = "/hts.v1.HtsService/GetIntegrityMetrics"
	HtsService_GetCellActivity_FullMethodName     = "/hts.v1.HtsService/GetCellActivity"
)

// HtsServiceClient is the client API for HtsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HtsService, iç tüketiciler için gRPC yüzeyidir.
//
// REST handler'ları (ADR-12/1) aynı servis katmanını çağırır; ikisi arasında
// kod üretimi yoktur.
type HtsServiceClient interface {
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	GetCells(ctx context.Context, in *GetCellsRequest, opts ...grpc.CallOption) (*GeoJsonResponse, error)
	GetEstimates(ctx context.Context, in *GetEstimatesRequest, opts ...grpc.CallOption) (*GeoJsonResponse, error)
	GetFindings(ctx context.Context, in *GetFindingsRequest, opts ...grpc.CallOption) (*GeoJsonResponse, error)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	GetIntegrityMetrics(ctx context.Context, in *GetIntegrityMetricsRequest, opts ...grpc.CallOption) (*GetIntegrityMetricsResponse, error)
	GetCellActivity(ctx context.Context, in *GetCellActivityRequest, opts ...grpc.CallOption) (*GetCellActivityResponse, error)
}

type htsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHtsServiceClient(cc grpc.ClientConnInterface) HtsServiceClient {
	return &htsServiceClient{cc}
}

func (c *htsServiceClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, HtsService_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *htsServiceClient) GetCells(ctx context.Context, in *GetCellsRequest, opts ...grpc.CallOption) (*GeoJsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeoJsonResponse)
	err := c.cc.Invoke(ctx, HtsService_GetCells_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *htsServiceClient) GetEstimates(ctx context.Context, in *GetEstimatesRequest, opts ...grpc.CallOption) (*GeoJsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeoJsonResponse)
	err := c.cc.Invoke(ctx, HtsService_GetEstimates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *htsServiceClient) GetFindings(ctx context.Context, in *GetFindingsRequest, opts ...grpc.CallOption) (*GeoJsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeoJsonResponse)
	err := c.cc.Invoke(ctx, HtsService_GetFindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *htsServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, HtsService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *htsServiceClient) GetIntegrityMetrics(ctx context.Context, in *GetIntegrityMetricsRequest, opts ...grpc.CallOption) (*GetIntegrityMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIntegrityMetricsResponse)
	err := c.cc.Invoke(ctx, HtsService_GetIntegrityMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *htsServiceClient) GetCellActivity(ctx context.Context, in *GetCellActivityRequest, opts ...grpc.CallOption) (*GetCellActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCellActivityResponse)
	err := c.cc.Invoke(ctx, HtsService_GetCellActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HtsServiceServer is the server API for HtsService service.
// All implementations must embed UnimplementedHtsServiceServer
// for forward compatibility.
//
// HtsService, iç tüketiciler için gRPC yüzeyidir.
//
// REST handler'ları (ADR-12/1) aynı servis katmanını çağırır; ikisi arasında
// kod üretimi yoktur.
type HtsServiceServer interface {
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	GetCells(context.Context, *GetCellsRequest) (*GeoJsonResponse, error)
	GetEstimates(context.Context, *GetEstimatesRequest) (*GeoJsonResponse, error)
	GetFindings(context.Context, *GetFindingsRequest) (*GeoJsonResponse, error)
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	GetIntegrityMetrics(context.Context, *GetIntegrityMetricsRequest) (*GetIntegrityMetricsResponse, error)
	GetCellActivity(context.Context, *GetCellActivityRequest) (*GetCellActivityResponse, error)
	mustEmbedUnimplementedHtsServiceServer()
}

// UnimplementedHtsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHtsServiceServer struct{}

func (UnimplementedHtsServiceServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedHtsServiceServer) GetCells(context.Context, *GetCellsRequest) (*GeoJsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCells not implemented")
}
func (UnimplementedHtsServiceServer) GetEstimates(context.Context, *GetEstimatesRequest) (*GeoJsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEstimates not implemented")
}
func (UnimplementedHtsServiceServer) GetFindings(context.Context, *GetFindingsRequest) (*GeoJsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFindings not implemented")
}
func (UnimplementedHtsServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedHtsServiceServer) GetIntegrityMetrics(context.Context, *GetIntegrityMetricsRequest) (*GetIntegrityMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIntegrityMetrics not implemented")
}
func (UnimplementedHtsServiceServer) GetCellActivity(context.Context, *GetCellActivityRequest) (*GetCellActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCellActivity not implemented")
}
func (UnimplementedHtsServiceServer) mustEmbedUnimplementedHtsServiceServer() {}
func (UnimplementedHtsServiceServer) testEmbeddedByValue()                    {}

// UnsafeHtsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HtsServiceServer will
// result in compilation errors.
type UnsafeHtsServiceServer interface {
	mustEmbedUnimplementedHtsServiceServer()
}

func RegisterHtsServiceServer(s grpc.ServiceRegistrar, srv HtsServiceServer) {
	// If the following call panics, it indicates UnimplementedHtsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HtsService_ServiceDesc, srv)
}

func _HtsService_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HtsServiceServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HtsService_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HtsServiceServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HtsService_GetCells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCellsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HtsServiceServer).GetCells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HtsService_GetCells_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HtsServiceServer).GetCells(ctx, req.(*GetCellsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HtsService_GetEstimates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEstimatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HtsServiceServer).GetEstimates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HtsService_GetEstimates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HtsServiceServer).GetEstimates(ctx, req.(*GetEstimatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HtsService_GetFindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HtsServiceServer).GetFindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HtsService_GetFindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HtsServiceServer).GetFindings(ctx, req.(*GetFindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HtsService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HtsServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HtsService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HtsServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HtsService_GetIntegrityMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIntegrityMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HtsServiceServer).GetIntegrityMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HtsService_GetIntegrityMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HtsServiceServer).GetIntegrityMetrics(ctx, req.(*GetIntegrityMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HtsService_GetCellActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCellActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HtsServiceServer).GetCellActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HtsService_GetCellActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HtsServiceServer).GetCellActivity(ctx, req.(*GetCellActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HtsService_ServiceDesc is the grpc.ServiceDesc for HtsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HtsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hts.v1.HtsService",
	HandlerType: (*HtsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRuns",
			Handler:    _HtsService_ListRuns_Handler,
		},
		{
			MethodName: "GetCells",
			Handler:    _HtsService_GetCells_Handler,
		},
		{
			MethodName: "GetEstimates",
			Handler:    _HtsService_GetEstimates_Handler,
		},
		{
			MethodName: "GetFindings",
			Handler:    _HtsService_GetFindings_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _HtsService_GetMetrics_Handler,
		},
		{
			MethodName: "GetIntegrityMetrics",
			Handler:    _HtsService_GetIntegrityMetrics_Handler,
		},
		{
			MethodName: "GetCellActivity",
			Handler:    _HtsService_GetCellActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hts/v1/hts.proto",
}
